// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-npPkeY0InjcKMNgBtY7fW13_3N60Cd4',
    appId: '1:470516067456:web:3abbe1b17fdbc025614a65',
    messagingSenderId: '470516067456',
    projectId: 'icd-kaa-olx',
    authDomain: 'icd-kaa-olx.firebaseapp.com',
    storageBucket: 'icd-kaa-olx.appspot.com',
    measurementId: 'G-273W9P7N0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENty3oR_jN80dr5gU0Y1pR4PkmfxuzEI',
    appId: '1:470516067456:android:14ccf712bbd87595614a65',
    messagingSenderId: '470516067456',
    projectId: 'icd-kaa-olx',
    storageBucket: 'icd-kaa-olx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSVoY-gAPjdSmqh3bQfMGorqDDECtfqY',
    appId: '1:470516067456:ios:04a01fcc201704e3614a65',
    messagingSenderId: '470516067456',
    projectId: 'icd-kaa-olx',
    storageBucket: 'icd-kaa-olx.appspot.com',
    iosClientId: '470516067456-4u3d1m8ikl9f8uv52l42erstjmk59okf.apps.googleusercontent.com',
    iosBundleId: 'com.example.icdKaaOlx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSVoY-gAPjdSmqh3bQfMGorqDDECtfqY',
    appId: '1:470516067456:ios:04a01fcc201704e3614a65',
    messagingSenderId: '470516067456',
    projectId: 'icd-kaa-olx',
    storageBucket: 'icd-kaa-olx.appspot.com',
    iosClientId: '470516067456-4u3d1m8ikl9f8uv52l42erstjmk59okf.apps.googleusercontent.com',
    iosBundleId: 'com.example.icdKaaOlx',
  );
}
